version: '3'
services:
  k3s:
    image: rancher/k3s:v0.5.0
    command: server --https-listen-port 7777
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/config
    volumes:
    - $HOME/.kube:/output
    - k3s-server:/var/lib/rancher/k3s
    ports:
    - 7777:7777
    - 80:80

volumes:
  k3s-server: {}
